apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  selector:
    matchLabels:
      app: k8s-tutorial
      role: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: k8s-tutorial
        role: backend
    spec:
      containers:
      - name: backend
        image: vepo/backend:1.0.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  selector:
    app: k8s-tutorial
    role: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: k8s-tutorial
      role: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-tutorial
        role: frontend
    spec:
      containers:
      - name: frontend
        image: vepo/frontend:1.0.0
        ports:
        - containerPort: 8080
        env:
        - name: BACKEND_URL
          value: "http://backend-svc.default.svc.cluster.local:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  type: NodePort
  selector:
    app: k8s-tutorial
    role: frontend
  type: NodePort
  sessionAffinity: ClientIP
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080