apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    app: k8s-tutorial
    version: v1
    role: backend
    example: k8s
spec:
  containers:
  - name: backend
    image: vepo/backend:1.0.0
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: k8s-tutorial
    version: v1
    role: frontend
    example: k8s
spec:
  containers:
  - name: frontend
    image: vepo/frontend:1.0.0
    ports:
    - containerPort: 8080